"""
Django settings for pharmacy_management project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-69p1r!86f9sof$ugi+h*3jjk8i)fdh5)3olnx(5if=y-1zfi38'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['pharmecy.ezygrocery.com','www.pharmecy.ezygrocery.com','localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'unfold',
    'unfold.contrib.filters',
    'unfold.contrib.forms',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'pharmacy',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'pharmacy_management.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pharmacy_management.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'bn'

TIME_ZONE = 'Asia/Dhaka'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Unfold Admin Configuration
UNFOLD = {
    "SITE_TITLE": "Admin Panel",
    "SITE_HEADER": "Administration",
    "SITE_URL": "/",
    "SITE_SYMBOL": "speed",
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "ENVIRONMENT": "config.settings.environment_callback",
    "COLORS": {
        "primary": {
            "50": "250 245 255",
            "100": "243 232 255",
            "200": "233 213 255",
            "300": "216 180 254",
            "400": "192 132 252",
            "500": "168 85 247",
            "600": "147 51 234",
            "700": "126 34 206",
            "800": "107 33 168",
            "900": "88 28 135",
            "950": "59 7 100",
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": "ড্যাশবোর্ড",
                "separator": True,
                "items": [
                    {
                        "title": "হোম",
                        "icon": "dashboard",
                        "link": lambda request: reverse_lazy("admin:pharmacy-dashboard"),
                    },
                ],
            },
            {
                "title": "ডেটা ব্যবস্থাপনা",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "রোগী",
                        "icon": "people",
                        "link": lambda request: reverse_lazy("admin:pharmacy_patient_changelist"),
                    },
                    {
                        "title": "ভিজিট",
                        "icon": "event_note",
                        "link": lambda request: reverse_lazy("admin:pharmacy_visit_changelist"),
                    },
                    {
                        "title": "ওষুধ",
                        "icon": "medication",
                        "link": lambda request: reverse_lazy("admin:pharmacy_medicine_changelist"),
                    },
                    {
                        "title": "ক্রয়",
                        "icon": "shopping_cart",
                        "link": lambda request: reverse_lazy("admin:pharmacy_purchase_changelist"),
                    },
                    {
                        "title": "বিক্রয়",
                        "icon": "point_of_sale",
                        "link": lambda request: reverse_lazy("admin:pharmacy_sale_changelist"),
                    },
                ],
            },
            {
                "title": "রিপোর্ট",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "ক্রয় রিপোর্ট",
                        "icon": "receipt_long",
                        "link": lambda request: reverse_lazy("admin:pharmacy-purchase-report"),
                    },
                    {
                        "title": "বিক্রয় রিপোর্ট",
                        "icon": "assessment",
                        "link": lambda request: reverse_lazy("admin:pharmacy-sale-report"),
                    },
                    {
                        "title": "ভিজিট রিপোর্ট",
                        "icon": "description",
                        "link": lambda request: reverse_lazy("admin:pharmacy-visit-report"),
                    },
                ],
            },
            {
                "title": "দ্রুত অ্যাকশন",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "নতুন বিক্রয়",
                        "icon": "add_shopping_cart",
                        "link": lambda request: reverse_lazy("admin:pharmacy_sale_add"),
                    },
                    {
                        "title": "নতুন ভিজিট",
                        "icon": "add_circle",
                        "link": lambda request: reverse_lazy("admin:pharmacy_visit_add"),
                    },
                    {
                        "title": "নতুন ক্রয়",
                        "icon": "add_box",
                        "link": lambda request: reverse_lazy("admin:pharmacy_purchase_add"),
                    },
                    {
                        "title": "কম স্টক",
                        "icon": "warning",
                        "link": lambda request: f"{reverse_lazy('admin:pharmacy_medicine_changelist')}?stock_quantity__lte=5",
                        "badge": lambda request: get_low_stock_count(),
                    },
                ],
            },
        ],
    },
}

def environment_callback(request):
    return ["ডেভেলপমেন্ট", "success"]

from django.urls import reverse_lazy
from django.templatetags.static import static
from django.utils import timezone

# Import Medicine model for badge count (lazy import to avoid circular dependency)
def get_low_stock_count():
    try:
        from pharmacy.models import Medicine
        return Medicine.objects.filter(stock_quantity__lte=5).count()
    except:
        return 0