# Generated by Django 5.2.6 on 2025-10-24 15:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ওষুধের নাম')),
                ('company', models.CharField(blank=True, max_length=100, verbose_name='কোম্পানি')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='একক দাম')),
                ('stock_quantity', models.IntegerField(default=0, verbose_name='স্টক পরিমাণ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='তৈরির তারিখ')),
            ],
            options={
                'verbose_name': 'ওষুধ',
                'verbose_name_plural': 'ওষুধসমূহ',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='রোগীর নাম')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='ফোন নম্বর')),
                ('address', models.TextField(blank=True, verbose_name='ঠিকানা')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='তৈরির তারিখ')),
            ],
            options={
                'verbose_name': 'রোগী',
                'verbose_name_plural': 'রোগীরা',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='পরিমাণ')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='একক খরচ')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='মোট খরচ')),
                ('purchase_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='কেনার তারিখ')),
                ('supplier', models.CharField(blank=True, max_length=100, verbose_name='সরবরাহকারী')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.medicine', verbose_name='ওষুধ')),
            ],
            options={
                'verbose_name': 'ক্রয়',
                'verbose_name_plural': 'ক্রয়সমূহ',
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='ভিজিটের তারিখ')),
                ('prescription', models.TextField(blank=True, verbose_name='প্রেসক্রিপশন')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.patient', verbose_name='রোগী')),
            ],
            options={
                'verbose_name': 'ভিজিট',
                'verbose_name_plural': 'ভিজিটসমূহ',
                'ordering': ['-visit_date'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='পরিমাণ')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='একক দাম')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='মোট দাম')),
                ('payment_type', models.CharField(choices=[('cash', 'নগদ'), ('credit', 'বাকি')], default='cash', max_length=10, verbose_name='পেমেন্ট ধরন')),
                ('sale_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='বিক্রয়ের তারিখ')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.medicine', verbose_name='ওষুধ')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.visit', verbose_name='ভিজিট')),
            ],
            options={
                'verbose_name': 'বিক্রয়',
                'verbose_name_plural': 'বিক্রয়সমূহ',
            },
        ),
    ]
