"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-6#obp93i+kmuwcld94antk_5u#=or5=-pno7zthl2$lul=x#6s'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']  # Add your hosts here


# Application definition

INSTALLED_APPS = [
    "unfold",  # before django.contrib.admin
    "unfold.contrib.filters",  # optional, if special filters are needed
    "unfold.contrib.forms",  # optional, if special form elements are needed
    "unfold.contrib.inlines",  # optional, if special inlines are needed
    "unfold.contrib.import_export",  # optional, if django-import-export package is used
    "unfold.contrib.guardian",  # optional, if django-guardian package is used
    "unfold.contrib.simple_history",  # optional, if django-simple-history package is used
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'pharmacy',
]

UNFOLD = {
    "WYSIWYG_OPTIONS": {
        "selector": "textarea",
        "plugins": "link image code",
        "toolbar": "undo redo | bold italic | alignleft aligncenter alignright | code",
    },
}
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',


            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'bn-bd'  # বাংলা ভাষার জন্য

TIME_ZONE = 'Asia/Dhaka'  # বাংলাদেশ টাইমজোন

USE_I18N = True

USE_L10N = True

USE_TZ = True

# বাংলা ভাষা সাপোর্ট
LANGUAGES = [
    ('bn', 'Bengali'),
    ('en', 'English'),
]

LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

LOGIN_URL = '/auth/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# Session settings for cart
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_AGE = 1209600  # 2 weeks
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django Unfold Configuration
from django.templatetags.static import static
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _

UNFOLD = {
    "SITE_TITLE": " Admin Panel",
    "SITE_HEADER": " Administration",
    "SITE_URL": "/",
    "SITE_SYMBOL": "speed",
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "ENVIRONMENT": "config.settings.environment_callback",
    "COLORS": {
        "primary": {
            "50": "252 254 235",   # Very light lime
            "100": "247 252 213",  # Light lime
            "200": "238 248 178",  # Lighter lime
            "300": "226 242 142",  # Light lime green
            "400": "208 234 106",  # Medium lime
            "500": "196 216 46",   # Main lime color (#c4d82e)
            "600": "168 184 42",   # Darker lime
            "700": "140 154 35",   # Dark lime
            "800": "112 123 28",   # Darker
            "900": "84 92 21",     # Very dark lime
            "950": "56 61 14",     # Darkest lime
        },
    },
    "STYLES": [
        lambda request: static("admin/css/custom_sidebar.css"),
        lambda request: static("admin/css/custom_tabs.css"),
    ],
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": "ড্যাশবোর্ড",
                "separator": True,
                "items": [
                    {
                        "title": "হোম",
                        "icon": "dashboard",
                        "link": lambda request: reverse_lazy("admin:pharmacy-dashboard"),
                    },
                ],
            },
            {
                "title": "ডেটা ব্যবস্থাপনা",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "রোগী",
                        "icon": "people",
                        "link": lambda request: reverse_lazy("admin:pharmacy_patient_changelist"),
                    },
                    {
                        "title": "ভিজিট",
                        "icon": "event_note",
                        "link": lambda request: reverse_lazy("admin:pharmacy_visit_changelist"),
                    },
                    {
                        "title": "ওষুধ",
                        "icon": "medication",
                        "link": lambda request: reverse_lazy("admin:pharmacy_medicine_changelist"),
                    },
                    {
                        "title": "ক্রয়",
                        "icon": "shopping_cart",
                        "link": lambda request: reverse_lazy("admin:pharmacy_purchase_changelist"),
                    },
                    {
                        "title": "বিক্রয়",
                        "icon": "point_of_sale",
                        "link": lambda request: reverse_lazy("admin:pharmacy_sale_changelist"),
                    },
                ],
            },
            {
                "title": "রিপোর্ট",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "ক্রয় রিপোর্ট",
                        "icon": "receipt_long",
                        "link": lambda request: reverse_lazy("admin:pharmacy-purchase-report"),
                    },
                    {
                        "title": "বিক্রয় রিপোর্ট",
                        "icon": "assessment",
                        "link": lambda request: reverse_lazy("admin:pharmacy-sale-report"),
                    },
                    {
                        "title": "ভিজিট রিপোর্ট",
                        "icon": "description",
                        "link": lambda request: reverse_lazy("admin:pharmacy-visit-report"),
                    },
                ],
            },
            {
                "title": "দ্রুত অ্যাকশন",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "নতুন বিক্রয়",
                        "icon": "add_shopping_cart",
                        "link": lambda request: reverse_lazy("admin:pharmacy_sale_add"),
                    },
                    {
                        "title": "নতুন ভিজিট",
                        "icon": "add_circle",
                        "link": lambda request: reverse_lazy("admin:pharmacy_visit_add"),
                    },
                    {
                        "title": "নতুন ক্রয়",
                        "icon": "add_box",
                        "link": lambda request: reverse_lazy("admin:pharmacy_purchase_add"),
                    },
                    {
                        "title": "কম স্টক",
                        "icon": "warning",
                        "link": lambda request: f"{reverse_lazy('admin:pharmacy_medicine_changelist')}?stock_quantity__lte=5",
                        "badge": lambda request: get_low_stock_count(),
                    },
                ],
            },
        ],
    },

}
